# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none



#variables:
  


  # Azure Resource Manager connection created during pipeline creation
#  azureSubscription: '2c814482-e174-47a3-a7ec-8fa1be163b68'

  # Web app name
#  webAppName: 'webapp-dev-ApimWebAppTerraform-client'

  # Environment name
#  environmentName: 'dev'

  # Agent VM image name
#  vmImageName: 'ubuntu-latest'



stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: 'ubuntu-latest'
      environment: dev
    variables:
      - group: L-SAFNC-SACredit-apresentacao-Dev  # Correctly reference the variable group here
 

    steps:
    - checkout: self

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo "Mostra variavel"
          echo $(environmentName)

    - template: templates/download-securefile.yml
      parameters:
            environmentName: "$(environmentName)"
            certificatepassword: $(certificate-password)

    - task: CopyFiles@2
      displayName: 'Copy File oauth-client-dev.key to artifact staging directory'
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: 'oauth-client-$(environmentName).key'
        TargetFolder: $(System.DefaultWorkingDirectory)/src/main/resources/
      name: CopyFiles            

    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: '*App* | Replace tokens in **/*.properties'
      inputs:
            rootDirectory: ''
            targetFiles: '**/application.properties'

    # - task: replacetokens@5
    #   inputs:
    #     targetFiles: '**/application.properties'
    #     encoding: 'auto'
    #     tokenPattern: 'custom'
    #     actionOnMissing: 'warn'
    #     keepToken: false
    #     actionOnNoFiles: 'continue'
    #     enableTransforms: false
    #     enableRecursion: false
    #     useLegacyPattern: false
    #     enableTelemetry: true
    #     customReplaceTokens: |



    # - task: qetza.replacetokens.replacetokens-task.replacetokens@4
    #   displayName: 'Replace Tokens in Configuration Files'
    #   inputs:
    #     rootDirectory: '$(System.DefaultWorkingDirectory)' # Set this to the root directory where your files are located
    #     targetFiles: '**/*.config' # Update this pattern to match your configuration file(s)
    #     tokenPrefix: '#{'
    #     tokenSuffix: '}#'
    #     keepToken: false # Set this to 'true' if you want to keep the token in the file after replacement
    #   env:
    #     ReplaceTokens_VariableGroupName: 'L-SAFNC-SACredit-apresentacao-Dev' # Specify your variable group name

    - task: Maven@3
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        codeCoverageToolOption: 'jaCoCo'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        options: 'package -Dmaven.test.skip'


 





    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      displayName: faz upload da pasta Build.ArtifactStagingDirectory para artefato criado chamado drop
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJavaApp
    displayName: Deploy Java Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: webpessoalspring'
            inputs:
              azureSubscription: 'Azure subscription 1 (2c814482-e174-47a3-a7ec-8fa1be163b68)'
              appType: 'webApp'
              appName: 'webapp-dev-ApimWebAppTerraform-client'
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
              deploymentMethod: 'auto'
